version: '3'
services:
  web:
    environment:
      - SCRAPE_URL=http://scraper:5000/scrape
    build: ./web-app
    ports:
      - "3000:5000"
  
  scraper:
    build: ./web-scraper
    ports:
      - "3001:5000"